# <ins> Feature engineering file </ins>

In [5]:
# Import libraries
import pandas as pd
import numpy as np

# Load the cleaned dataset
df = pd.read_csv('../data/processed/heart_cleaned.csv')
df.head()

AttributeError: partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)

<b> Label Encoding: Sex and ExerciseAngina </b>

In [ ]:
# Mapping Sex with Male: 0 and Female:1
sex_mapping = {'M': 0, 'F': 1}
df['Sex'] = df['Sex'].str.strip().map(sex_mapping)
print('Sex feature has been label encoded to binary values')

exercise_angina_mapping = {'N': 0, 'Y': 1}
df['ExerciseAngina'] = df['ExerciseAngina'].str.strip().map(exercise_angina_mapping)
print('ExerciseAngina feature has been label encoded to binary values')

df.head()

Sex feature has been label encoded to binary values
ExerciseAngina feature has been label encoded to binary values

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,ATA,140.0,289.0,0,Normal,172,0,0.0,Up,0
1,49,1,NAP,160.0,180.0,0,Normal,156,0,1.0,Flat,1
2,37,0,ATA,130.0,283.0,0,ST,98,0,0.0,Up,0
3,48,1,ASY,138.0,214.0,0,Normal,108,1,1.5,Flat,1
4,54,0,NAP,150.0,195.0,0,Normal,122,0,0.0,Up,0

<b> One-hot Encoding: ChestPainType, RestingECG and ST_Slope </b>

In [ ]:
encoded_df = pd.get_dummies(df, columns=['ChestPainType', 'RestingECG', 'ST_Slope'], drop_first=True)
encoded_df.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,0,140.0,289.0,0,172,0,0.0,0,True,False,False,True,False,False,True
1,49,1,160.0,180.0,0,156,0,1.0,1,False,True,False,True,False,True,False
2,37,0,130.0,283.0,0,98,0,0.0,0,True,False,False,False,True,False,True
3,48,1,138.0,214.0,0,108,1,1.5,1,False,False,False,True,False,True,False
4,54,0,150.0,195.0,0,122,0,0.0,0,False,True,False,True,False,False,True

In [ ]:
encoded_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   Sex                918 non-null    int64
 2   RestingBP          918 non-null    float64
 3   Cholesterol        918 non-null    float64
 4   FastingBS          918 non-null    int64
 5   MaxHR              918 non-null    int64
 6   ExerciseAngina     918 non-null    int64
 7   Oldpeak            918 non-null    float64
 8   HeartDisease       918 non-null    int64
 9   ChestPainType_ATA  918 non-null    int64
 10  ChestPainType_NAP  918 non-null    int64
 11  ChestPainType_TA   918 non-null    int64
 12  RestingECG_Normal  918 non-null    int64
 13  RestingECG_ST      918 non-null    int64
 14  ST_Slope_Flat      918 non-null    int64
 15  ST_Slope_Up        918 non-null    int64
dtypes: float64(3), int64(13)
memory usage: 114.9 KB

In [ ]:
bool_columns = encoded_df.select_dtypes(include='bool').columns
encoded_df[bool_columns] = encoded_df[bool_columns].astype(int)

In [ ]:
# encoded_df.to_csv('heart_encoded.csv', index=False)

# <ins>Feature Creation</ins>

In [ ]:
df = pd.read_csv('heart_encoded.csv')
df.head()

NameError: name 'pd' is not defined